import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { useState, useEffect } from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Currency Converter</title>
        <meta name="description" content="A simple browser-based Currency Converter in Next.JS. Initially generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.center}>
          Currency Converter
        </div>
        <div className={styles.description}>
          A simple browser-based Currency Converter
        </div>
      </main>
    </>
  )
}
